from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
import settings
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^Ceryx/$','ceryx.website.views.index'),
    (r'^Ceryx/DroidSans.woff/$','ceryx.DroidSans-webfont.woff'),
    (r'^Ceryx/DroidSans.ttf/$','ceryx.DroidSans-webfont.ttf'),
    (r'^Ceryx/DroidSans.svg/$','ceryx.DroidSans-webfont.svg'),
    (r'^save/$','ceryx.website.views.save'),
    (r'^Editorial$','ceryx.website.views.editorial'),
    (r'^Ceryx/world$','ceryx.website.views.world'),
    (r'^Ceryx/politics$','ceryx.website.views.politics'),
    (r'^Ceryx/technology$','ceryx.website.views.tech'),                   
    (r'^Ceryx/lifestyle$','ceryx.website.views.life'),
    (r'^Ceryx/business$','ceryx.website.views.business'),
    (r'^Ceryx/sports$','ceryx.website.views.sports'),
    (r'^Ceryx/media$','ceryx.website.views.media'),                   
    (r'^Ceryx/ourTechnology$','ceryx.website.views.ourTech'),
    (r'^Ceryx/blog$','ceryx.website.views.blog'),
    (r'^Ceryx/aboutUs$','ceryx.website.views.aboutUs'),                   
    (r'^Ceryx/World1$','ceryx.website.views.world1'),
    (r'^Ceryx/World2$','ceryx.website.views.world2'),
    (r'^Ceryx/World3$','ceryx.website.views.world3'),
    (r'^Ceryx/World4$','ceryx.website.views.world4'),
    (r'^Ceryx/World5$','ceryx.website.views.world5'),
    (r'^Ceryx/World6$','ceryx.website.views.world6'),                   
    (r'^Ceryx/Media1$','ceryx.website.views.media1'),
    (r'^Ceryx/Media2$','ceryx.website.views.media2'),
    (r'^Ceryx/Media3$','ceryx.website.views.media3'),
    (r'^Ceryx/Media4$','ceryx.website.views.media4'),
    (r'^Ceryx/Media5$','ceryx.website.views.media5'),
    (r'^Ceryx/Media6$','ceryx.website.views.media6'),
    (r'^Ceryx/Politics1$','ceryx.website.views.politics1'),
    (r'^Ceryx/Politics2$','ceryx.website.views.politics2'),
    (r'^Ceryx/Politics3$','ceryx.website.views.politics3'),
    (r'^Ceryx/Politics4$','ceryx.website.views.politics4'),
    (r'^Ceryx/Politics5$','ceryx.website.views.politics5'),
    (r'^Ceryx/Politics6$','ceryx.website.views.politics6'),
    (r'^Ceryx/Sports1$','ceryx.website.views.sports1'),
    (r'^Ceryx/Sports2$','ceryx.website.views.sports2'),
    (r'^Ceryx/Sports3$','ceryx.website.views.sports3'),
    (r'^Ceryx/Sports4$','ceryx.website.views.sports4'),
    (r'^Ceryx/Sports5$','ceryx.website.views.sports5'),
    (r'^Ceryx/Sports6$','ceryx.website.views.sports6'),
    (r'^Ceryx/Business1$','ceryx.website.views.business1'),
    (r'^Ceryx/Business2$','ceryx.website.views.business2'),
    (r'^Ceryx/Business3$','ceryx.website.views.business3'),
    (r'^Ceryx/Business4$','ceryx.website.views.business4'),
    (r'^Ceryx/Business5$','ceryx.website.views.business5'),
    (r'^Ceryx/Business6$','ceryx.website.views.business6'),
    (r'^Ceryx/Tech1$','ceryx.website.views.tech1'),
    (r'^Ceryx/Tech2$','ceryx.website.views.tech2'),
    (r'^Ceryx/Tech3$','ceryx.website.views.tech3'),
    (r'^Ceryx/Tech4$','ceryx.website.views.tech4'),
    (r'^Ceryx/Tech5$','ceryx.website.views.tech5'),
    (r'^Ceryx/Tech6$','ceryx.website.views.tech6'),
    (r'^Ceryx/Lifestyle1$','ceryx.website.views.lifestyle1'),
    (r'^Ceryx/Lifestyle2$','ceryx.website.views.lifestyle2'),
    (r'^Ceryx/Lifestyle3$','ceryx.website.views.lifestyle3'),
    (r'^Ceryx/Lifestyle4$','ceryx.website.views.lifestyle4'),
    (r'^Ceryx/Lifestyle5$','ceryx.website.views.lifestyle5'),
    (r'^Ceryx/Lifestyle6$','ceryx.website.views.lifestyle6'),
    # Examples:
    # url(r'^$', 'ceryx.views.home', name='home'),
    # url(r'^ceryx/', include('ceryx.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
